# docker-compose.yaml
version: '3.7'

volumes:
  orderer.ayurvedic.com:
  peer0.farmers.ayurvedic.com:
  peer0.collectors.ayurvedic.com:
  peer0.labs.ayurvedic.com:

networks:
  ayurvedic:
    name: fabric_ayurvedic

services:
  orderer.ayurvedic.com:
    container_name: orderer.ayurvedic.com
    image: hyperledger/fabric-orderer:2.4.7
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/ordererOrganizations/ayurvedic.com/orderers/orderer.ayurvedic.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/ayurvedic.com/orderers/orderer.ayurvedic.com/tls/:/var/hyperledger/orderer/tls
      - orderer.ayurvedic.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
    networks:
      - ayurvedic

  peer0.farmers.ayurvedic.com:
    container_name: peer0.farmers.ayurvedic.com
    image: hyperledger/fabric-peer:2.4.7
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_ayurvedic
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.farmers.ayurvedic.com
      - CORE_PEER_ADDRESS=peer0.farmers.ayurvedic.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.farmers.ayurvedic.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.farmers.ayurvedic.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.farmers.ayurvedic.com:7051
      - CORE_PEER_LOCALMSPID=FarmersOrgMSP
    volumes:
      - ../organizations/peerOrganizations/farmers.ayurvedic.com/peers/peer0.farmers.ayurvedic.com/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/farmers.ayurvedic.com/peers/peer0.farmers.ayurvedic.com/tls:/etc/hyperledger/fabric/tls
      - peer0.farmers.ayurvedic.com:/var/hyperledger/production
      - /var/run/docker.sock:/host/var/run/docker.sock
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 7054:7054
    networks:
      - ayurvedic

  api:
    container_name: ayurvedic-api
    image: node:16-alpine
    working_dir: /app/api
    command: sh -c "npm install --silent && node server.js"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - ALLOWED_ORIGINS=http://localhost:3000
      - MOCK_BLOCKCHAIN=true
    volumes:
      - ./:/app
      - ./wallet:/app/wallet
      - ./organizations:/app/organizations
    ports:
      - 3000:3000
    networks:
      - ayurvedic
    depends_on: []